### ISSUE TITLE
Query.requireCount vs Query.requireCounts

### ISSUE THREAD

**Issue by wwalraven** [syncfusion/ej2-data#2]
The API documentation for Query describes a property 'requiresCount'. In fact, it is called 'requiresCounts' in the implementation, which is actually a misspelling, I believe.

The ej2-data package is described as 
"A package of Essential JS 2 DataManger to perform data operations in client application."

This should be
"A package of Essential JS 2 **DataManager** to perform data operations in **a** client application."

**Comment by RamdhasUeikattan** [comment]
Hi wwalraven 

Query 1: The API documentation for Query describes a property 'requiresCount'. In fact, it is called 'requiresCounts' in the implementation, which is actually a misspelling, I believe.

In the Query class, “requiresCount” is a method which is used to enable the requiresCounts property. Please refer to the below API link.

API Link: http://ej2.syncfusion.com/15.4.17/documentation/data/api-query.html?lang=typescript#requirescount 

Query 2: The ej2-data package description mistake

Thanks for your suggestion, we will update our project description.

Regards,
Ramdhas  Ueikattan

**Comment by wwalraven** [comment]
Hi Ramdhas,

Thank you for your response. I think my confusion stems from the generated query _sent to the server_ containing a property called 'requiresCounts' which is not documented anywhere that I could find.

In other words, you're exposing an internal implementation detail that does not match the documentation. If someone implements a data source, encountering the internal name for the property is unexpected.

Thank you,
Walt

**Comment by RamdhasUeikattan** [comment]
Hi Walt,
 
Thanks for your update.
 
Query 1: I think my confusion stems from the generated query sent to the server containing a property called 'requiresCounts'.
 
Currently, documentation for server parameter is not available. We will update the server parameters in our documentation in any of our upcoming releases.
 
Query 2: you're exposing an internal implementation detail that does not match the documentation. If someone implements a data source, encountering the internal name for the property is unexpected.
 
Thanks for your suggestion, We have considered "Need to rename requiresCount property" as a defect and the fix will be available in our November last week release.
 
Regards,
Ramdhas  Ueikattan.

**Comment by dhivyasyncfusion** [comment]
Hi Walt,

Thanks for your patience.

We are glad to announce that our **v15.4.20-preview** release is rolled out successfully. In this release, we have added the fix for “**Need to rename requiresCount property**” issue. We have renamed **Query.requiresCounts** to **Qurey.isCountRequired**

https://github.com/syncfusion/ej2-data/releases/tag/v15.4.20-preview

Please let us know if you have any queries.

Regards,
R.Dhivya
